### ISSUE TITLE
Using webpack alias w/ next-pwa `_app.tsx` causes error

### ISSUE THREAD

**Issue by harshzalavadiya** [shadowwalker/next-pwa#17]
First of all thank you for making amazing `next-pwa` plugin

webpack aliases works fine when using it in other files w/ using `next-pwa` but when we use any alias import in `_app.tsx` causes compilation error

```txt
[ error ] ./src/pages/_app.tsx
Module not found: Can't resolve '@components/@core/container' in '/home/x/git/biodiv-ui-next/src/pages'
```

Error was introduced in latest release, worked fine in `2.1.2` w/ latest `next`

**Minimal reproduction project**
https://github.com/harshzalavadiya/next-pwa-error-app-tsx

**OS** linux
**NodeJS** 12.16.0 LTS
**Yarn** 1.x Latest

**Comment by shadowwalker** [comment]
Hi, I cloned your error reproduction project, there was a missing `const path = require('path')` in your `next.config.js`. After I fix that and run `yarn build`, everything works fine. Could not repro the error.
Could you try remove `node_modules` and reinstall the dependencies?

**Comment by shadowwalker** [comment]
Never mind, I just found out the error was on dev time. I will fix it.

**Comment by shadowwalker** [comment]
Just complete the fix, can you try out version `2.2.0`?

**Comment by harshzalavadiya** [comment]
@shadowwalker that was fast :zap:
`2.2.0` works like a charm thank you for such fast resolution
