### ISSUE TITLE
Uncaught (in promise) bad-precaching-response: bad-precaching-response middleware-manifest.json

### ISSUE THREAD

**Issue by alirezavlz** [shadowwalker/next-pwa#291]
Similar to https://github.com/shadowwalker/next-pwa/issues/177 but in next 12 It tries to load `_next/server/middleware-manifest.json` on client.

**Comment by alirezavlz** [comment]
I tried this but it doesn't work

```js
pwa: {
    disable: isDev,
    dest: 'public',
    reloadOnOnline: false,
    runtimeCaching: defaultCache,
    publicExcludes: ['!middleware*.json']
},

```

**Comment by blackroom24** [comment]
#288 is the same issue try looking into it.

**Comment by viennv1709** [comment]
You have the same issue

**Comment by ciceropablo** [comment]
Same here.

**Comment by dwfee** [comment]
same here

**Comment by ksenginew** [comment]
same

**Comment by JuniYadi** [comment]
try this example: https://github.com/shadowwalker/next-pwa/issues/288#issuecomment-955777098
it's working for me

**Comment by captain-woof** [comment]
@JuniYadi Thanks, that worked for me!

**Comment by L1lith** [comment]
None of these fixes worked for me. I'm exporting statically. It would be really nice to be able to use this library.

**Comment by ksenginew** [comment]
> None of these fixes worked for me. I'm exporting statically. It would be really nice to be able to use this library.

@L1lith try this
```js
// next.config.js
const withPWA = require("next-pwa");
const runtimeCaching = require("next-pwa/cache");

module.exports = withPWA({
  pwa: {
    runtimeCaching,
    buildExcludes: [/middleware-manifest\.json$/]
  },
});
```

**Comment by L1lith** [comment]
> > None of these fixes worked for me. I'm exporting statically. It would be really nice to be able to use this library.
> 
> @L1lith try this
> 
> ```js
> // next.config.js
> const withPWA = require("next-pwa");
> const runtimeCaching = require("next-pwa/cache");
> 
> module.exports = withPWA({
>   pwa: {
>     runtimeCaching,
>     buildExcludes: [/middleware-manifest\.json$/]
>   },
> });
> ```
> 
> This worked for me. Ask me for any help.

I set that config, but when I run it I still can't get the worker to run successfully, now instead of the middleware-manifest.json related error it now says:
```
Could not load worker TypeError: e.split is not a function
    NextJS 42
        moduleUrl
        $createWorkerFromOldConfig
        l
        createWorker
        $startWorker
        $onChangeMode
        setMode
        loadModule
        setMode
        componentDidMount
        uo
        ku
        unstable_runWithPriority
        Hl
        wu
        ou
        Xl
        unstable_runWithPriority
        Hl
        Xl
        Yl
        cu
        Xu
        hydrate
        be
        be
        e
        l
        _invoke
        S
        j
        a
        C
        C
        fe
        pe
        e
        l
        _invoke
        S
        j
        a8a28b14e-e0bcf10bae6d7a04.js:1:51965
```
I'm not sure if this is the same issue or not but I'm on Next-PWA@5.4.0 and Next@12.0.3

**Comment by matthewlilley** [comment]
Still appears to be an issue.

**Comment by shadowwalker** [comment]
Should be working now with latest version and no buildExcludes config needed.

**Comment by matthewlilley** [comment]
Thanks @shadowwalker! I'll check it out quicky.

**Comment by priyansharma** [comment]
Please Help, I also get this same issue and I try many way to solve it but nothing is happening
![issueGit from 2022-07-12 10-47-07](https://user-images.githubusercontent.com/55691501/178418700-ac8b2908-a5b7-4604-b6f4-fca889f2706c.jpg)

**Comment by priyansharma** [comment]
My problem is solved after update next-pwa from 5.4.1 to 5.5.4
